version: '3.7'
services:
  app:
    image: $CI_REGISTRY_IMAGE:$APP_VERSION.$CI_PIPELINE_ID
    ports:
      - "8080:8080"
  test:
    image: curlimages/curl:8.13.0
    command: /bin/sh -c "sleep 10 && curl -s http://app:8080/ -i -vvv"
